languageCode = 'en-gb'
disableKinds = ['taxonomy', 'term']
intro = true
title = "ian ahuja"
headline = "ian ahuja"
description = "ian ahuja"
baseURL = "https://ianahuja.com"
contentDir = "content"
github = "https://github.com/12ian34"
twitter = "https://x.com/12ian34"
email = "12ian34@example.com"
opengraph = true
shareTwitter = true
buildFuture = true
[markup]
  [markup.goldmark.renderer]
    unsafe = true
[params]
  blog_title = "words"
  og_type = "website"
  og_locale = "en_GB"
  og_title = "ian ahuja"
  og_site_name = "ian ahuja"
  og_article_author = "ian ahuja"
  og_description = "ian ahuja's projects"
  og_image = "images/PXL_20230501_122853688_fun4.png"
  default_keywords = "ian, ahuja, ianahuja, moonquake, music, supper clubs, supper, club, restaurant, london, tech, chess"

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  supperclubs = "/supperclubs/:slug/"