[build]
  publish = "public"
  command = "hugo"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  HUGO_VERSION = "v0.154.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"